-- Notas
INSERT INTO PUBLIC.NOTA(VERSION, NAME, VALUE, DISABLED) VALUES (0, 'Test 001', 'Test 001 - value', false);
INSERT INTO PUBLIC.NOTA(VERSION, NAME, VALUE, DISABLED) VALUES (0, 'Test 002', 'Test 002 - value', false);
INSERT INTO PUBLIC.NOTA(VERSION, NAME, VALUE, DISABLED) VALUES (0, 'Test 003', 'Test 003 - value', false);
